from python:3.6.1-alpine

WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app
COPY ./gunicorn.py /usr/src/app/gunicorn.py
COPY ./website /usr/src/app/website
COPY ./config /usr/src/app/config

# install additional deps on top of alpine required by bcrypt and Pillow (jpeg-dev)
# TODO: remove these deps after bcrypt installed to create smaller image
RUN apk add --no-cache gcc libffi libffi-dev libc-dev openssl-dev jpeg-dev

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

ENV ENV=dev
ENV PYTHONUNBUFFERED=true

EXPOSE 8000

CMD ["/usr/local/bin/gunicorn", "--config=gunicorn.py", "website.app:get_app()"]
