version: '3.5'
services:
  webpack:
    build:
      context: .
      dockerfile: Dockerfile-webpack
    volumes:
      - ./web:/usr/src/app
    restart: unless-stopped
    ports:
      - "8181:8181"
      - "8081:8081"
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    volumes:
      - .:/usr/src/app
      - ./web:/usr/src/app/web
      - ${PHOTO_DESTINATION:-./photos}:/photos
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8000:8000"
  mongo:
    image: "mongo:3.4.5"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - db-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS:-admin}

volumes:
  db-volume:
