name: deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: '1.18.1'

    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - run: doctl registry login --expiry-seconds 600

    - run: go version

    - run: go vet .

    - shell: bash
      run: |
        docker build . -t registry.digitalocean.com/jketcham/website:$GITHUB_SHA
        docker push registry.digitalocean.com/jketcham/website:$GITHUB_SHA

    - name: DigitalOcean App Platform deployment
      uses: digitalocean/app_action@v1.1.2
      with:
        app_name: website
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        images: '[
          {
            "name": "website",
            "image":{
              "registry_type": "DOCR",
              "repository": "jketcham",
              "tag": "${{ github.sha }}"
            },
          },
        ]'
